# Generated by Django 5.0.1 on 2025-12-11 06:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Departamento/Estado')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('amenities', models.TextField(blank=True, help_text='Separadas por comas', verbose_name='Amenidades')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Descripción Corta')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('registration_start', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Registro')),
                ('registration_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Registro')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('ongoing', 'En Curso'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('is_free', models.BooleanField(default=False, verbose_name='¿Es Gratuito?')),
                ('is_online', models.BooleanField(default=False, verbose_name='¿Es Virtual?')),
                ('online_url', models.URLField(blank=True, verbose_name='URL del Evento Virtual')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='Banner')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/', verbose_name='Miniatura')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Términos y Condiciones')),
                ('tags', models.CharField(blank=True, help_text='Separadas por comas', max_length=500, verbose_name='Etiquetas')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Número de Vistas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.category', verbose_name='Categoría')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='events_even_status_dfba18_idx'), models.Index(fields=['category', 'status'], name='events_even_categor_f85a11_idx'), models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx')],
            },
        ),
    ]
