# Generated by Django 5.0.1 on 2025-12-11 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('document_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Documento')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Documento')),
                ('status', models.CharField(choices=[('registered', 'Registrado'), ('checked_in', 'Check-in Realizado'), ('no_show', 'No Asistió'), ('cancelled', 'Cancelado')], default='registered', max_length=20, verbose_name='Estado')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Check-in')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Requerimientos Especiales')),
                ('dietary_restrictions', models.CharField(blank=True, max_length=200, verbose_name='Restricciones Alimentarias')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de Contacto de Emergencia')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto de Emergencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_attendees', to=settings.AUTH_USER_MODEL, verbose_name='Check-in Realizado Por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event', verbose_name='Evento')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='tickets.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Check-in')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('device_info', models.CharField(blank=True, max_length=500, verbose_name='Información del Dispositivo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_logs', to='attendees.attendee', verbose_name='Asistente')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='Realizado Por')),
            ],
            options={
                'verbose_name': 'Registro de Check-in',
                'verbose_name_plural': 'Registros de Check-in',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('closed', 'Cerrada')], default='draft', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='¿Es Anónima?')),
                ('allow_multiple_responses', models.BooleanField(default=False, verbose_name='¿Permitir Múltiples Respuestas?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Texto de la Pregunta')),
                ('question_type', models.CharField(choices=[('text', 'Texto Libre'), ('rating', 'Calificación (1-5)'), ('yes_no', 'Sí/No'), ('multiple_choice', 'Opción Múltiple'), ('checkbox', 'Casillas de Verificación')], max_length=20, verbose_name='Tipo de Pregunta')),
                ('options', models.JSONField(blank=True, help_text='Para preguntas de opción múltiple o checkbox', null=True, verbose_name='Opciones')),
                ('is_required', models.BooleanField(default=False, verbose_name='¿Es Obligatoria?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='attendees.survey', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta de Encuesta',
                'verbose_name_plural': 'Preguntas de Encuesta',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, verbose_name='Respuesta de Texto')),
                ('rating_response', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calificación')),
                ('choice_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta de Selección')),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='attendees.attendee', verbose_name='Asistente')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='attendees.surveyquestion', verbose_name='Pregunta')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondiente')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuesta',
                'ordering': ['-responded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['event', 'status'], name='attendees_a_event_i_fa9de7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['user', 'event'], name='attendees_a_user_id_a964d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('user', 'event')},
        ),
    ]
