# Generated by Django 5.0.1 on 2025-12-11 06:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Total')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad Vendida')),
                ('min_purchase', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Compra Mínima')),
                ('max_purchase', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Compra Máxima')),
                ('sale_start', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Venta')),
                ('sale_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Venta')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('benefits', models.TextField(blank=True, help_text='Separados por comas', verbose_name='Beneficios')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Tipo de Ticket',
                'verbose_name_plural': 'Tipos de Tickets',
                'ordering': ['price'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], max_length=20, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Descuento')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usos Máximos')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Veces Usado')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Usos Máximos por Usuario')),
                ('valid_from', models.DateTimeField(verbose_name='Válido Desde')),
                ('valid_until', models.DateTimeField(verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Compra Mínima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='events.event', verbose_name='Evento')),
                ('applicable_ticket_types', models.ManyToManyField(blank=True, related_name='discount_codes', to='tickets.tickettype', verbose_name='Tipos de Ticket Aplicables')),
            ],
            options={
                'verbose_name': 'Código de Descuento',
                'verbose_name_plural': 'Códigos de Descuento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('used', 'Usado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='active', max_length=20, verbose_name='Estado')),
                ('attendee_name', models.CharField(max_length=200, verbose_name='Nombre del Asistente')),
                ('attendee_email', models.EmailField(max_length=254, verbose_name='Email del Asistente')),
                ('attendee_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Asistente')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento Aplicado')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='tickets/qr/', verbose_name='Código QR')),
                ('pdf_ticket', models.FileField(blank=True, null=True, upload_to='tickets/pdf/', verbose_name='Ticket PDF')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.discountcode', verbose_name='Código de Descuento')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype', verbose_name='Tipo de Ticket')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['code'], name='tickets_tic_code_2520cc_idx'), models.Index(fields=['status', 'ticket_type'], name='tickets_tic_status_15be59_idx'), models.Index(fields=['buyer', 'status'], name='tickets_tic_buyer_i_ef0999_idx')],
            },
        ),
    ]
