# Generated by Django 5.0.1 on 2025-12-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='max_purchase',
            field=models.PositiveIntegerField(default=10, verbose_name='Máximo por compra'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='min_purchase',
            field=models.PositiveIntegerField(default=1, verbose_name='Mínimo por compra'),
        ),
    ]
