# Generated by Django 5.0.1 on 2025-12-11 06:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industria')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de Contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('contact_position', models.CharField(blank=True, max_length=100, verbose_name='Cargo del Contacto')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('facebook', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=200, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=200, verbose_name='LinkedIn')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='NIT/RUT')),
                ('billing_address', models.TextField(blank=True, verbose_name='Dirección de Facturación')),
                ('status', models.CharField(choices=[('prospect', 'Prospecto'), ('active', 'Activo'), ('inactive', 'Inactivo'), ('blacklisted', 'Lista Negra')], default='prospect', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('tags', models.CharField(blank=True, help_text='Separadas por comas', max_length=500, verbose_name='Etiquetas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Mínimo')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Máximo')),
                ('color', models.CharField(default='#FFD700', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('benefits_description', models.TextField(blank=True, verbose_name='Descripción de Beneficios')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel de Patrocinio',
                'verbose_name_plural': 'Niveles de Patrocinio',
                'ordering': ['order', '-min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('contract_signed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Firma de Contrato')),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='sponsorships/contracts/', verbose_name='Documento de Contrato')),
                ('logo_placement', models.CharField(blank=True, help_text='Dónde se mostrará el logo del patrocinador', max_length=200, verbose_name='Ubicación del Logo')),
                ('booth_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Stand')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impresiones')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('leads_generated', models.PositiveIntegerField(default=0, verbose_name='Leads Generados')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='events.event', verbose_name='Evento')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='sponsors.sponsor', verbose_name='Patrocinador')),
                ('sponsor_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships', to='sponsors.sponsortier', verbose_name='Nivel de Patrocinio')),
            ],
            options={
                'verbose_name': 'Patrocinio',
                'verbose_name_plural': 'Patrocinios',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'sponsor')},
            },
        ),
        migrations.CreateModel(
            name='SponsorBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('logo_placement', 'Ubicación de Logo'), ('booth_space', 'Espacio de Stand'), ('tickets', 'Tickets Gratuitos'), ('social_media', 'Mención en Redes Sociales'), ('email_blast', 'Email a Asistentes'), ('speaking_slot', 'Espacio para Charla'), ('branding', 'Branding en Evento'), ('other', 'Otro')], max_length=50, verbose_name='Tipo de Beneficio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('delivered', models.BooleanField(default=False, verbose_name='¿Entregado?')),
                ('delivered_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('proof_of_delivery', models.FileField(blank=True, null=True, upload_to='sponsorships/benefits/', verbose_name='Comprobante de Entrega')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='sponsors.sponsorship', verbose_name='Patrocinio')),
            ],
            options={
                'verbose_name': 'Beneficio de Patrocinio',
                'verbose_name_plural': 'Beneficios de Patrocinio',
                'ordering': ['sponsorship', 'benefit_type'],
            },
        ),
    ]
